words:
  - autodocs
  - avenir
  - beziers
  - centi
  - cjsx
  - clsx
  - cosθ
  - csstype
  - ctsx
  - deadband
  - dedupe
  - dicebear
  - esbuild
  - eslintcache
  - geolocation
  - globby
  - grayscale
  - greyscale
  - hookz
  - janky
  - Jsons
  - logomark
  - lucide
  - Memoji
  - MERCHANTABLITY
  - metaball
  - mjsx
  - mtsx
  - nextjs
  - nodenext
  - nosync
  - notionists
  - ofetch
  - Ookla
  - opennext
  - opennextjs
  - Picsum
  - pkgs
  - reekystive
  - rollup
  - sinθ
  - sonner
  - squircle
  - stspr
  - tanstack
  - trpc
  - tsgo
  - turbopack
  - unplugin
  - usehooks
  - usestateref
  - vaul
  - Vercel
  - Vite
  - vitejs
  - Vitest
  - WCAG
  - webp
  - workerd
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
  - cloudflare-env.d.ts
  - pnpm-lock.yaml
