words:
  - autodocs
  - avenir
  - beziers
  - centi
  - clsx
  - cosθ
  - deadband
  - dedupe
  - dicebear
  - esbuild
  - grayscale
  - greyscale
  - hookz
  - janky
  - logomark
  - lucide
  - MERCHANTABLITY
  - nextjs
  - nodenext
  - notionists
  - opennext
  - opennextjs
  - Picsum
  - pkgs
  - reekystive
  - sinθ
  - sonner
  - squircle
  - tanstack
  - trpc
  - turbopack
  - unplugin
  - usehooks
  - usestateref
  - vaul
  - Vercel
  - Vite
  - vitejs
  - Vitest
  - WCAG
  - webp
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
  - cloudflare-env.d.ts
  - pnpm-lock.yaml
